@startuml sequence_empleado_eliminar
title Secuencia: Eliminar Empleado

actor Cliente as User
participant "EmpleadoController" as Ctrl
participant "EmpleadoService" as Srv
participant "EmpleadoRepository (In-Memory)" as Repo

User -> Ctrl : DELETE /api/v1/empleados/{id}
activate Ctrl
Ctrl -> Srv : eliminarEmpleado(id)
activate Srv
Srv -> Repo : existsById(id)  // O findById para verificar y luego eliminar
activate Repo
Repo --> Srv : existe (boolean)
deactivate Repo

alt empleadoExiste
  Srv -> Repo : deleteById(id) // o cambiar estado a INACTIVO y save()
  activate Repo
  Repo --> Srv : void
  deactivate Repo
  Srv --> Ctrl : void
else noExiste
  Srv --> Ctrl : throw ResourceNotFoundException("Empleado no encontrado con id: " + id)
end

deactivate Srv

alt empleadoEliminado
  Ctrl --> User : HTTP 204 No Content
else ResourceNotFoundException
  Ctrl --> User : HTTP 404 Not Found
end
deactivate Ctrl

@enduml
